name: R

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        R: [ '4.2.2' ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: Setup R env
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}

      - name: Build R API
        run: |
          cd R && make example
      
