name: ARMv8

on:
  workflow_call:

  
jobs:
  CppARMV8:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: openGPMP on ARMv8
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: initalize github repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Test openGPMP install on ubuntu ARMv8
        run: |
          #cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd build && sudo make
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
      
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"


