name: Debian

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  CppARMV6:
    uses: ./.github/workflows/ARMV6cpp.yml

  CppARMv7:
    uses: ./.github/workflows/ARMV7cpp.yml

  CppARMv8:
    uses: ./.github/workflows/ARMV8cpp.yml

  CppRPI:
    uses: ./.github/workflows/cpp_rpi.yml

  CppPPC64LE:
    uses: ./.github/workflows/PPC64LEcpp.yml

  CppRISCV:
    uses: ./.github/workflows/RISCVcpp.yml

  CppS390X:
    uses: ./.github/workflows/S390Xcpp.yml

  Source-Linux-Build:
    runs-on: [ ubuntu-latest ]
    needs: [CppARMV6,CppARMV7,CppARMV8,CppRPI,CppPPC64LE,CppRISCV,CppS390X]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
