name: Codecov analysis

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install deps
        run: | 
          sudo apt install lcov cmake gfortran
      
      - name: Configure
        run: |
          sudo apt-get install libgtest-dev && 
          cd /usr/src/gtest && 
          sudo cmake CMakeLists.txt && 
          sudo make && 
          cd /usr/src/gtest/lib &&
          sudo cp -a libgtest.a libgtest_main.a /usr/lib && 
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && 
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a 

      - name: gtest on openGPMP
        run: |
          mkdir build && cd build
          cmake -S ../ -DBUILD_TESTS=ON && make

      - name: Copy Code Coverage File
        run: |
          cp build/tests/lcov.info .coverage/

      - name: Codecov Sync
        uses: codecov/codecov-action@v3
        with:
          files: .coverage/lcov.info
          name: codecov-umbrella
          functionalities: fixes
          verbose: true

      - uses: actions/upload-artifact@v4
        with:
          name: LCOV
          path: .coverage/lcov.info
