name: RasCore

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: initalize github repo
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Test Python on ARMv8 Raspbian
        uses: docker/build-push-action@v3
        with:
          context: .
          file: scripts/Dockerfile.cpprpi.raspi_latest
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmtpkarmv8:latest

