name: openGPMP CUDA

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        
    - name: Execute CUDA
      run: |
        echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
        echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
        nvcc modules/linalg/_gpu_mtx_add.cu
