name: Build Doxygen Documentation

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: LCOV_FILES
          path: docs/
      
      - name: Dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gcovr lcov cppcheck tree
          ls -lash .coverage
          tree
        
      - name: Copy HTML Static Analysis and Unit Test Coverage
        run: |
          tree docs
          #make docs-analysis
          #cp -r docs/testing docs/doxygen/html
          #cp -r docs/analysis docs/doxygen/html
          #tree docs
          #make docs-testcov

      - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/doxygen/html
          config_file: Doxyfile

      - name: Copy HTML Static Analysis and Unit Test Coverage
        run: |
          tree docs
          cp -r docs/analysis/ docs/doxygen/html/
          cp -r docs/testing docs/doxygen/html/
          tree docs
