name: NixPy

on:
  push:
    branches: [ main, dev ]
  #pull_request:
  #  branches: [ main , dev ]
  
jobs:
  PyNix:
    name: Test openMTPK on Linux
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Test openMTPK install
        run: |
          pip install openmtpk
          # confirm samples run
          cd samples/python 
          for f in *.py; do python3 "$f"; done 

