name: RasPy

on:
  #push:
  #  branches: [ main, dev ]
  #pull_request:
  #  branches: [ main, dev ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: initalize github repo
        uses: actions/checkout@v3

      - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - 
        name: Initialize Raspberry Pi OS ARMv8 Image
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite_arm64:latest
          commands: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt-get install -y python3 python3-distutils python3-pip python3-apt python3-dev
            pip install openmtpk
            cd samples/python
            for f in *.py; do python3 "$f"; done
      - 
        name: Get platform info
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)
