name: Python

on:
  push:
    branches: [ main , dev]
  #pull_request:
  #  branches: [ main , dev ]
  
jobs:
  deploy:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          if [ "$RUNNER_OS" == "macOS" ] ; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install Swig
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ] ; then
            sudo apt-get install swig
          elif [ "$RUNNER_OS" == "macOS" ] ; then
            brew install swig
          else
            echo "OS ERROR"
            exit 1
          fi

          #cd Python/openmtpk &&
          #make run-swig
          #python3 setup.py build_ext --inplace
          #make compile 
          #make compile-wrapper 
          #make compile-lib

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ] ; then
            python setup.py sdist bdist_wheel --plat-name=manylinux1_x86_64 build_ext --inplace
            tree
          elif [ "$RUNNER_OS" == "macOS" ] ; then
            python setup.py sdist bdist_wheel --plat-name=darwin build_ext --inplace
          fi
          twine upload --repository pypi dist/*

