name: Python

on:
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]
  
jobs:
  deploy:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

          #if [ "$RUNNER_OS" == "macOS" ] ; then
          #  brew install python
          #fi

      - name: Install Swig
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ] ; then
            sudo apt-get install swig
          elif [ "$RUNNER_OS" == "macOS" ] ; then
            brew install swig
          else
            echo "OS ERROR"
            exit 1
          fi

          cd Python/openmtpk &&
          make run-swig
          python3 setup.py build_ext --inplace
          #make compile 
          #make compile-wrapper 
          #make compile-lib

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository pypi dist/*

