name: PyRISCV64

on:
  push:
    branches: [ main , dev ]
  #pull_request:
  #  branches: [ main , dev ]
  
jobs:
  PyNix:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Test openMTPK Python on RISCV64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Test openMTPK install on ubuntu RISCV64
        run: | 
          pip install openmtpk
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"


